### PR TITLE
edit last sentence in delivery section of lifecycle

### LINKED ISSUE #62: Analytical lifecycle: Last sentence of 5.1.4. is vague
Depending on the commission, impact, approval processes and the nature of the project, work in this phase can vary considerably and may include summary packs, documentation to facilitate repeatability, *or consideration of governance, version control and maintenance.*

Governance, version control and maintenance should have been considered at previous stages, so it is unclear why they are specifically mentioned here

### PR DESCRIPTION
**Pull request by irisoren-sg**
Close #62

### CODE REVIEW

**Comment by Hurstharrier** [comment]
@irisoren-sg  I have reviewed the wording. A few suggestions, to put the subjects at the beginning of the sentence. I don't think they have altered the intent or meaning.

During the delivery phase, insights and analytical assurances are communicated to the Approver and the Commissioner. The aim is ensuring they are sufficiently understood in order for them to determine whether the work has been appropriately assured and meets their requirements. This may the trigger additional analysis and further assurance as analytical projects frequently need further iteration or extension to satisfy the Commissioner's needs.

Work in this phase can vary considerably, depending on the commission, impact, approval processes and the nature of the project. The work may include producing summary packs, _documentation_ and knowledge management to facilitate repeatability, and / or consideration of governance, version control and maintenance.

Have a look and see what you think .If you are happy then use this and go ahead with the merge.

:) Alec

**Comment by Hurstharrier** [comment]
@irisoren-sg  - thanks - good point. I think that once documentation and knowledge management are in place then recovering the work should be possible. Therefore I think the issue of governance would lie with new work i.e. not in this phase. So I think we should remove the clause about governance etc. Having said that if the work is being stored with the likelihood that it will be redeployed in future (the MoD and DSTL have a lot of these type of models) then possible we should say something about this.

How about this:

"During the delivery stage, insights and analytical assurances are communicated to the Approver and the Commissioner. The aim is ensuring that these are sufficiently understood in order for the Approver and Commissioner to determine whether the work has been appropriately assured and meets their requirements. This may then trigger additional analysis and further assurance as analytical projects frequently need further iteration or extension to satisfy the Commissioner's needs.

In some cases, models may be held in abeyance with a strong likelihood that they will be reused. In these cases, in these cases regular reviews may be used to ensure they can be brought back into use when required by, for example, ensuring they are compatible with current software and hardware."

**Comment by irisoren-sg** [comment]
@Hurstharrier You make a valid point. But I think that this is a point to be added in the Delivery chapter as it is detailed. The analytical lifecycle chapter should only be giving a cursory overview to each stage. So I have added a new issue #221 to add the text to the delivery chapter. And the Analytical Lifecycle chapter text It now reads

> During the delivery stage, insights and analytical assurances are communicated to the Approver and the Commissioner. The aim is ensuring that these are sufficiently understood in order for the Approver and Commissioner to determine whether the work has been appropriately assured and meets their requirements. This may then trigger additional analysis and further assurance as analytical projects frequently need further iteration or extension to satisfy the Commissioner's needs.
> 
> Work in this stage can vary considerably depending on the commission, impact, approval processes and the nature of the project. Delivery and communication activities may include producing summary packs and reports, launching dashboards or websites and presentations to boards.

>

**Comment by Hurstharrier** [comment]
Iris

Spot on  - clear thinking as always.

A


***@***.***

Alec Waterhouse [he/him] | Energy Statistics
Tel: 0300 068 2929 | 0778 994 7785 | ***@***.***
***@***.***%0b>

**Pull request merged**
