### PR TITLE
138 definitions ai ml and black box

### PR DESCRIPTION
**Pull request by Hurstharrier**
I have added definitions for AI and ML and black box model but haven't put in hyperlinks

### CODE REVIEW

**Comment by irisoren-sg** [comment]
@Hurstharrier  Apologies, I have forgotten what we discussed pre-leave, Were we wanting to put AI and ML in definitions, and black-box in a box? I can add this to the PR and merge, if you confirm

**Review by irisoren-sg — COMMENTED** [review]
The definitions are clear. But do we want Black Box as a boxed definition linked to AI and ML

**Comment by irisoren-sg** [comment]
Added black-box as a call-out box and hyperlinks to it

**Comment by rebecca-wodcke-gad** [comment]
I agree that this complicates things. Suggested a commit where black box is just be another definition, with hyperlinks to the AI and ML definitions
Also linked to AI from the ML definition

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad The more I think about it, I wonder if whether the black-box term is an added compllication? It feels like a term that we like, but is not critical to understanding what is needed for delivering quality analysis. @Hurstharrier made the point that we want to be referring to all models whose working is not apparent. But at present, are there any models except for AI/ML that fall under this category?
In Part 2 chapters, we use the terms AI/ML

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg I'd be happy to remove, I think it has negative connotations, from a pre-AI world where black box was synonymous with poorly understood

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad I can look at this tomorrow and make sure that it is consistent in later chapters

**Comment by Hurstharrier** [comment]
@irisoren-sg @rebecca-wodcke-gad @zarbspace 
We did say we would address "black box models" so we do need to have the definition in. Happy to not have the hyper links.
The main point is what to do with analysis that  uses methods that are difficult to verify using traditional methods. i.e. black box.

AI and ML are good examples but they are not the only ones so the question is how to make what we say applicable to all.

**Comment by irisoren-sg** [comment]
@Hurstharrier @rebecca-wodcke-gad  I will accept these changes. But proposed to then change the part 2 chapter subheadings from "AI/ML and X stage" to "Black-box models and X stage". Otherwise it would mean that we do not use the term "black-box" models in later chapters. I will add an issue to change the references to AI/ML in other chapters - which should be done after many of the outstanding PRs have been merged

**Pull request merged**
