### PR TITLE
Design issues

### LINKED ISSUE #97: Design: Clarify commissioners role - level of mandation
[https://best-practice-and-impact.github.io/aqua_book_revision/design.html#the-commissioners-responsibilities-during-design](url)

Think this ought to be phrased a can or may

The Commissioner _may_ review the plan. They should agree with the Analyst that their approach will satisfy their requirements.

### LINKED ISSUE #137: Definitions: Do we want to remove "Quaility Assurance Plan"
The Design section only refers to an analytical plan, and includes assurance activities as part of this. We need to decide if introducing a separate Assurance Plan is beneficial or if we only refer to an Analytical plan. 

If we decide that having an Assurance plan separate to Analytical plan is beneficial we need to add this as an output of the design phase, and amend the list of what the Analytical plan considers.

If we decide to only have an Analytical plan, we need to remove this from the definitions, and amend the Analysis section that refers to it (either on Main after merging [PR ](https://github.com/best-practice-and-impact/aqua_book_revision/pull/135), or on the branch fix_#73_analysis_edits

### PR DESCRIPTION
**Pull request by irisoren-sg**
close #97 
close #137

### CODE REVIEW

**Review by Hurstharrier — CHANGES_REQUESTED** [review]
@irisoren-sg  
On the analysis.qmd - think it should read "The Analyst shall conduct the verification and validation activities"
On the design.qmd - if the Commissioner responsibility to review the plan is a "may" statement then shouldn't the rest of the statements also be "may ir.e. "may sign-off" and "may agree with the Analyst that the proposed approach..."

**Comment by irisoren-sg** [comment]
@Hurstharrier 
re: analysis.qmd I have added this to #214 
re: your suggestion for design.qmd. I am inclined to go with "The Commissioner may review the analytical plan.  They should  confirm that the analytical approach will satisfy their needs." I.e. They may or may not review the analytical plan in detail. However, it is recommended that they provide some sort of confirmation that the approach meets their needs.

Thoughts?

**Comment by Hurstharrier** [comment]
@irisoren-sg I agree your suggestion looks good. The important thing is that they confirm that what the Analyst is going to do will meet their needs.
One thought though now that I have said it should we reverse the order of the sentence to put the most important thing first.

It would read something like this.
The Commissioner should confirm with the Analyst that the analytical approach will satisfy their needs. The Commissioner may also review the analytical plan.

**Comment by irisoren-sg** [comment]
@Hurstharrier  Changed to "The Commissioner should confirm that the analytical approach will satisfy their needs. To assist in this, the Commissioner may review the analytical plan."

**Pull request merged**
